name: build
on:
  push:
    branches: ["main"]

env:
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: scheiblingco
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: scheibling
          password: ${{ env.PASSWORD }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/scheiblingco/smtp-relay:latest
            ghcr.io/scheiblingco/smtp-relay:0.5.0
            docker.io/scheibling/smtp-relay:latest
            docker.io/scheibling/smtp-relay:0.5.0

      